### ISSUE TITLE
vcf.properties for unit tests?

### ISSUE THREAD

**Issue by dwward** [mebbert/VariantToolChest#2]
I was going to give this source code a try and I encountered two hurdles.  Could not find the jsr dependency that was specified in the pom.xml file so I installed it to the classpath manually by google searching for it.  Second issue was when I tried to execute the JUnit tests there was a missing vcf.properties file.  I didn't dig into things too deeply but are there any easy resolutions to those issues?

**Comment by mebbert** [comment]
Donald,

Thank you for letting us know. We will look at this tomorrow. 

In the meantime you can add "-DskipTests=true" to the maven command. Then it should compile. 

—
Mark T. W. Ebbert 

Please excuse the brevity. Sent from my Zack Morris Phone.

**Comment by mwadswor** [comment]
Donald,

I just went through and fixed the jsc repository problem.  I also added instructions for what the VTC.properties file needs to look like near the bottom of the readme file under the "Compiling" section.  Could delete your clone and re-clone it, add the VTC.properties file and compile it?  Let me know if my fixes worked for you or not.

Thanks,

Mark Wadworth
